package fr.uga.l3miage.pc.prisonersdilemma.classes.game.model;

public enum TypeStrategieEnum {
    ADAPTATIF,
    ALEATOIRE,
    DONNANTDONNANT,
    DONNANTDONNANTALEATOIRE,
    DONNANTDONNANTDEUX,
    DONNANTDONNANTDEUXALEATOIRE,
    DONNANTDONNANTSOUPCONNEUX,
    GRADUEL,
    PACIFICATEURNAIF,
    PAVLOV,
    PAVLOVALEATOIRE,
    RANCUNNIER,
    RANCOUNIERDOUX,
    SONDEURNAIF,
    SONDEURREPENTANT,
    COOPERER,
    TRAHIR,
    VRAISPACIFICATEUR,
    UTILISATEUR
}
